# Test backend changes with Accel-Sim

name: Short-Tests-AccelSim

# Controls when the workflow will run
on:
  push:
    branches-ignore:
      - "gh-readonly-queue**"
  merge_group:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# By default regress against accel-sim's dev branch
env:
  ACCELSIM_BRANCH: dev

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-QV100:
    runs-on: ubuntu-latest
    container:
      image: tgrogers/accel-sim_regress:Ubuntu-22.04-cuda-11.7
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Run Simulation
        run: /bin/bash $GITHUB_WORKSPACE/short-tests-accelsim.sh

